// One-page site memo for a real-estate or expansion meeting. Code builds it
// from the grounded plan. The LLM writes only the summary and the per-site
// angles; every name and number in the memo comes from a Qloo result.
import type { SitePlan } from "../shared/types";

const pct = (x: number) => `${Math.round(x * 100)}`;
const bucket = (b: string) => b.replace(/_/g, " ").replace("and younger", "and under");

export function buildMemo(plan: SitePlan): string {
  const r = plan.request;
  const kind = r.format === "popup" ? "pop-up" : "store";
  const lines: string[] = [];
  lines.push(`# ${plan.brand}: ${plan.metro.name} ${kind} shortlist`);
  lines.push("");
  lines.push(plan.summary);
  lines.push("");
  const ents = plan.signals.filter((s) => s.kind === "entity").map((s) => s.name);
  const tags = plan.signals.filter((s) => s.kind === "tag").map((s) => s.name);
  lines.push(`**Audience signal.** ${[ents.length ? `Loves ${ents.join(", ")}` : "", tags.length ? `taste tags ${tags.join(", ")}` : ""].filter(Boolean).join("; ")}.`);
  if (plan.audience?.topAge) lines.push(`**Who.** Skews ${bucket(plan.audience.topAge)} (Qloo demographics, aggregate only).`);
  lines.push("");
  lines.push("| # | Neighbourhood | Site score | Lift vs baseline | Raw taste heat | Anchor places (affinity) | Partner brand |");
  lines.push("|---|---|---|---|---|---|---|");
  for (const s of plan.sites) {
    const anchors = s.anchors.slice(0, 3).map((a) => `${a.name} (${pct(a.affinity)})`).join(", ") || "none";
    const lift = s.neighborhood.lift !== undefined ? `${s.neighborhood.lift.toFixed(2)}×` : "n/a";
    lines.push(`| ${s.rank} | ${s.neighborhood.name} | ${pct(s.score)} | ${lift} | ${pct(s.neighborhood.heat)} | ${anchors} | ${s.brands[0]?.name ?? "none"} |`);
  }
  lines.push("");
  lines.push("## Why each site");
  for (const s of plan.sites) {
    lines.push("");
    lines.push(`**${s.rank}. ${s.neighborhood.name}.** ${s.angle}`);
    const why = s.why.map((w) => `${w.label} ${w.display ?? w.score.toFixed(2)}`).join("; ");
    if (why) lines.push(`Qloo signals: ${why}.`);
    const near = s.anchors.slice(0, 3).map((a) => `${a.name} (${a.distanceM} m from centre)`).join(", ");
    if (near) lines.push(`Co-marketing and anchor candidates: ${near}.`);
  }
  if (plan.metroCompare) {
    const { a, b, winner } = plan.metroCompare;
    lines.push("");
    lines.push("## Metro check");
    lines.push(`${a.name}: top-3 heat ${pct(a.topHeat)}, hot cells ${pct(a.hotShare)}%. ${b.name}: top-3 heat ${pct(b.topHeat)}, hot cells ${pct(b.hotShare)}%. Stronger fit: ${winner === a.metroId ? a.name : b.name}.`);
  }
  if (plan.audienceCompare) {
    const c = plan.audienceCompare;
    const lean = (side: "a" | "b" | "shared") => c.tags.filter((t) => t.lean === side).slice(0, 4).map((t) => t.name).join(", ") || "none";
    lines.push("");
    lines.push("## Audience check");
    lines.push(`Shared taste: ${lean("shared")}. Leans to ${c.a.map((s) => s.name).join(", ")}: ${lean("a")}. Leans to ${c.b.map((s) => s.name).join(", ")}: ${lean("b")}.`);
  }
  lines.push("");
  lines.push("## Next steps");
  lines.push(`- Walk the top ${Math.min(2, plan.sites.length)} neighbourhoods at peak hours and check vacancy and rent with a broker.`);
  lines.push("- Contact the anchor places for a co-hosted launch event before signing a lease.");
  lines.push("- Qloo gives taste affinity, not foot traffic, rent or vacancy. Check those with your broker.");
  lines.push("");
  lines.push(
    `_Data: Qloo Taste AI (${plan.provenance.qloo === "live" ? "live hackathon API" : "FIXTURE DATA, synthetic, not Qloo output"}). Planner: ${plan.provenance.llm}. Generated by Tasteplot._`,
  );
  return lines.join("\n");
}
